GET http://localhost:5000/courses

###
POST http://localhost:5000/courses
Content-Type: application/json

{
    "name": "bla",
    "dates": ["2020-12-01T22:00:00.000+00:00"]
}

###
PATCH http://localhost:5000/courses/5fbf7d0e6199a41658805954
Content-Type: application/json

{
    "dates": ["2020-12-22T22:00:00.000+00:00"]
}

###
GET http://localhost:5000/profile/8670224
//5fc4df9304fab9079397962f

###
GET http://localhost:5000/soldierCourses/8456304

###
POST http://localhost:5000/soldierCourses
Content-Type: application/json

{
    "pernum": "8670224",
    "courseId": "5f4f829891484226cdbc57d4",
    "date": "2021-09-13T21:00:00.000+00:00"
}

###
POST http://localhost:5000/profile
Content-Type: application/json

{
    "name": "Roy",
    "pernum": "8677696",
    "birthday": "2000-02-21",
    "rank": "סמל",
    "quote": "ima"
}